### ISSUE TITLE
Missing README documentation

### ISSUE THREAD

**Issue by jwflory** [tillioss/tilli-backend-server#5]
# Summary

Critical information about the project is missing in the repository `README.md` file

# Background

A README file is the front-door of an open source repository to the general public. It is where first impressions are made and how a visitor is directed to the place they want to go. Having an engaging README is helpful for building your project because it acts as a guide for a newcomer to understand the project, navigate the community, and understand where they can participate.

Additionally, the UNICEF Venture Fund also has specific requirements for a project `README.md` file in order for it to pass our 6-month and 12-month milestone review.

# Details

Referring to the UNICEF workplan, these are the requirements for a passing README:

* Overview or introduction to the specific repo where the README is found. What is it in everyday English?
* Developer environment instructions. How can you configure and set up a local environment? How do you set up this software?
* Explain how this specific repo connects into your overall product.
* Attribute all Open Source dependencies used to create what is hosted in the repository (including tools and frameworks).

# Outcome

* Enhanced entrypoints that make it easier for others to engage and connect with what is found in this GitHub repository
* Achieve a stronger baseline as an Open Source repository and project

**Comment by sakthiselvam-teqbahn** [comment]
Thanks Justin we are working on fixing the documentation.

**Comment by Tilliforkids** [comment]
Updated the readme and the descriptions
